### ISSUE TITLE
Testnet question

### ISSUE THREAD

**Issue by Xiaohong027** [dropil/dropilchain-testnet#1]
I found a began to recruit nodes for test the DROPIL testnet. https://dropil.com/. So cool~
Now I have app MVP code reference https://tutorials.cosmos.network and want to use several of my servers as nodes to run the blockchain testnet. How to convert from app code to node deployable code like this repository? THANKS SO MUCH!!

**Comment by dropil** [comment]
Hi @Xiaohong027, you can learn how to utilize Dropil Chain with our docs at [Dropil Chain Documentation](https://docs.dropilchain.com). We have a Telegram community where you can get help at [@DropilCoin](https://t.me/DropilCoin)

**Comment by Xiaohong027** [comment]
Thanks！
